require("rogedev.plugins-setup")
require("rogedev.core.options")
require("rogedev.core.keymaps")
require("rogedev.core.colorscheme")
require("rogedev.plugins.comment")
require("rogedev.plugins.nvim-tree")
require("rogedev.plugins.lualine")
require("rogedev.plugins.nvim-cmp")
require("rogedev.plugins.telescope")

